### ISSUE TITLE
Top News Theme Updates

### ISSUE THREAD

**Issue by rveitch** [openfcci/areavoices-network#19]
### Overview
Updates to the Top News Theme and related child themes.

#### Checklist
- [ ] Rebase/merge v1.08 custom changes into child theme (or in another method independent of the core theme) so that the core theme may be updated to v1.10.1 [#19]
- [x] Darken Body Typeface Color. [#21]
- [ ] Update Ad Code on Top News Child Themes. [#5]
- [x] Fix Nativo Ad Spot on Northland Outdoors. [#7]
- [ ] Featured Image Max/Thumbnail sizes & forced cropping on child themes. [#22]
- [ ] Fix Top News Theme mobile template override issue. [openfcci/fcc-northland-outdoors-radio#18]

**Comment by rveitch** [comment]
Issue moved to [openfcci/fcc-topnews-areavoices #2](https://github.com/openfcci/fcc-topnews-areavoices/issues/2) via [**ZenHub.io**](https://www.zenhub.io/)
