### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by rveitch** [openfcci/areavoices-network#2]
### Projects
- [ ] Global Navigation v1 #33 
- [ ] Elasticsearch
  - [ ] Launch Elasticsearch Server #32 
  - [ ] Elasticpress Integration #42
- [ ] Category System Redesign
  - [ ] New Category Hierarchy
  - [ ] Network-wide category syncing
  - [ ] Category Management - Permissions & Locking Update #14 
  - [ ] Give category edit access to all super admins #4
- [ ] Network Meta
  - [ ] Site category (w/ icon)
  - [ ] Site Owner
  - [ ] more/tba
- [ ] Cross-Site Publishing
- [ ] Analytics & AdOps
  - [ ] Analytics Dashboard UI
    - [ ] Google Analytics
    - [ ] Jetpack Stats
    - [ ] DFP
  - [ ] Tracking Code Manager Redesign
- [ ] AreaVoices.com - New Signup Form/Process #18
- [ ] Distribution Channels
  - [ ] AMP
  - [ ] Instant Articles
  - [ ] Apple News

### Tasks
- [ ] Featured Image / Body Image photo byline
- [ ] JW Player Updates
- [ ] WP Rest API (fix server conflicts)
- [ ] Top News Theme Updates

### Ongoing
- [ ] Github Enterprise Migration
  - [ ] Proposal / Benefits Outline
  - [ ] Migration Process Plan
  - [ ] Review Process
  - [ ] Integration / Unit Testing
- [ ] WP-Cli network management tools
- [ ] AreaVoices Theme Updates
- [ ] Network Standardization #39 
  - [ ] Site Options Standardization #8 
    - [ ] Site Options Sync #24 
  - [ ] Jetpack Options Standardization
  - [ ] Jetpack Modules Standardization
- [ ] Cavalcade Implementation (wp-cron replacement)
- [ ] Azure Migration

### Wishlist / Ideas
- [ ] AreaVoices Contributor - New User Setup/Tutorial Wizard #20 
- [ ] AreaVoices Help & Support System #13
